# Generated by Django 3.2.4 on 2021-07-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memeber_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=20)),
                ('member_email', models.EmailField(max_length=50)),
                ('member_contact', models.CharField(max_length=13)),
            ],
        ),
    ]
