# Generated by Django 3.2.5 on 2021-09-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='G_Image',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='media/index/images')),
            ],
        ),
    ]
