# Generated by Django 3.2.5 on 2021-09-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_g_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g_image',
            name='img',
            field=models.ImageField(upload_to='index/images/'),
        ),
    ]
